# Generated by Django 3.0.8 on 2020-07-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desctiption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
