# Generated by Django 3.0.8 on 2020-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_desctiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expirince',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='publishat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vanacy',
            field=models.IntegerField(default=1),
        ),
    ]
