# Generated by Django 3.0.8 on 2020-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200717_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salry',
            field=models.IntegerField(default=1000),
        ),
    ]
